- name: Create the directory for the application binaries.
  file: 
    path: "{{ optDirectory }}" 
    state: directory
    owner: pi
    group: pi

#- name: Download the application JAR file.
  get_url: 
    url: https://onebeartoe.ci.cloudbees.com/job/chronos/lastSuccessfulBuild/artifact/bouncy-clock/target/bouncy-clock-0.0.1-SNAPSHOT.jar
    dest: "{{ optDirectory }}"
