- name: Create the directory for the application binaries.
  file: 
    path: "{{ optDirectory }}" 
    state: directory
    owner: pi
    group: pi
    
- name: Copy the application JAR file.
  copy:
    src: target/bouncy-clock-0.0.1-SNAPSHOT.jar
    dest: "{{ optDirectory }}"
    mode: a+rwx