
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Maven Clean')
        {
            steps
            {
                echo "Cleaning..."

                sh '''
                    mvn clean
                '''
            }
        }
    }
}
