
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Build the application JAR file.')
        {
            steps
            {
                echo 'building the JAR...'

                sh '''
                    cd bouncy-clock/
                    mvn -DskipTests package
                '''
            }
        }

        stage('Update JAR')
        {
            steps
            {
                echo 'Updating the JAR...'

                sh '''
                    cd bouncy-clock/src/main/ansible/
                    cp ${ansible_inventory_path} .
                    ansible-playbook playbooks/jar.yml -i ansible-betoland.inventory -l bouncy-clock-pi
                '''
            }
        }
    }
}
